# Generated by Django 5.1.6 on 2025-02-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("biz_type", models.CharField(max_length=100)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="task_files/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
