# Generated by Django 5.1.6 on 2025-03-07 08:54

import django.db.models.deletion
import django.utils.timezone
import endpoint.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoint", "0002_caibaofile_company_task_source_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCREndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1024)),
                ("capacity", models.IntegerField(default=3)),
                ("current_load", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=endpoint.models._dynamic_upload_to
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="endpoint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="endpoint.ocrendpoint",
            ),
        ),
    ]
